  #这个字段需要填写，以使插件正常工作。请查看定价并登录 https://replicate.com/pricing。
  #api-token:
  
  #这是引用所使用的IA模型。如果您想更改IA模型，请查看：https://replicate.com/cjwbw/point-e/versions。
  model-version: 712f20305119ccc0df061a4ee130124e2d181ecc91cbcfed3ce372f3addb0ca3
  
  #进度条更新的时间间隔，以游戏刻为单位。
  progress-bar-update-time: 60
  
  #默认建筑大小。
  default-size: 30
  
  #每次进行平移时完成的角度（以度为单位）。
  angle-per-rotation: 10
  
  #每次进行平移时移动的方块数。
  blocks-per-translation: 2
  
  #增加建筑尺寸的大小。
  blocks-per-upsize: 5
  
  #每次迭代阈值的增加量。
  threshold-increase: 0.02
  
  #玩家创建建筑时使用的令牌。
  token-consumption:
    2d: 0
    prompt: 1
    low: 1
    mid: 2
    high: 5
